#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend aabdul
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 35755-web-01 34.207.212.223 check
    server 35755-web-02 3.85.41.174 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
